#!/bin/sh
# This script needs realpath, which is not installed on macos.
# Use https://github.com/harto/realpath-osx.git to get it.

for dir in $@; do
	test -d "$dir" || continue
	excl=$(realpath "$dir")/.dotignore
	for file in $dir/*; do
		file=$(realpath "$file")
		name=$(basename "$file")
		dest="$HOME/.$name"
		grep -qs "$name" "$excl" && continue
		test -e "$dest" || ln -vs "$file" "$dest"
	done
done
