#!/bin/sh

sc() {
	echo "show $1" | scutil \
		| sed -n "s/^  $2 : \(.*\)$/\1/p"
}

guid=$(sc State:/Network/Global/IPv4 PrimaryService)
name=$(sc Setup:/Network/Service/$guid UserDefinedName)
echo "$name"
